server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Hello Spring Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: lb://USER-SERVICE
          filters:
            - name: CustomFilter

        - id: product-service
          predicates:
            - Path=/product-service/**
          uri: lb://PRODUCT-SERVICE
          filters:
            - name: CustomFilter

        - id: order-service
          predicates:
            - Path=/order-service/**
          uri: lb://ORDER-SERVICE
          filters:
            - name: CustomFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7777/eureka
