spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7777/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome
server:
  port: 0